lint:
  files_exist:
    - assets/multiqc_config.yml
  files_unchanged:
    - .gitignore
    - assets/nf-core-plasmodiumdrugres_logo_light.png
    - docs/images/nf-core-plasmodiumdrugres_logo_light.png
    - docs/images/nf-core-plasmodiumdrugres_logo_dark.png
  multiqc_config: false
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: PlasmoGenEpi
  description: This pipeline takes PMO format and provides key metrics on supplied markers applicable to drug resistance
  force: false
  is_nfcore: true
  name: plasmodiumdrugres
  org: nf-core
  outdir: .
  version: 1.0.0
