---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: pmotools
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.12
  - pip
  - pip:
      - pmotools==1.0.0
