name: idm_wrapper
description: Estimate single-locus allele frequencies with the Incomplete Data Model (IDM)
keywords:
  - idm
  - slaf
  - allele frequency
tools:
  - idm_wrapper:
      description: |
        PGEcore Incomplete Data Model wrapper for SLAF estimation.
      homepage: https://github.com/PlasmoGenEpi/plasmodiumdrugres
      documentation: https://plasmogenepi.github.io/PGEcore/reference/IDM_wrapper.html
      licence: ["MIT"]
input:
  - aa_calls_input:
      type: file
      description: Amino acid call table (TSV)
      pattern: "*"
output:
  - slaf:
      - "${aa_calls_input.getBaseName(3)}.aa_slaf.tsv":
          type: file
          description: IDM single-locus allele frequency table (tuple with stub name)
          pattern: "${aa_calls_input.getBaseName(3)}.aa_slaf.tsv"
  - versions:
      - versions.yml:
          type: file
          description: Software versions
          pattern: versions.yml
authors:
  - "@PlasmoGenEpi"
maintainers:
  - "@PlasmoGenEpi"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/idm_wrapper:8fffb8098c99385c
      build_id: bd-8fffb8098c99385c_1
      scan_id: sc-6178d7a10cc9a358_1
    linux/arm64:
      name: community.wave.seqera.io/library/idm_wrapper:ad0d6ca77f66f5c6
      build_id: bd-ad0d6ca77f66f5c6_1
      scan_id: sc-2249e96edf40eef9_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/idm_wrapper:234a74738940ddf5
      build_id: bd-234a74738940ddf5_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/8d/8d36c36eac2443da4ffe45914b55136b2b4f0ffa444bb7dc3c1ce8cd7065525f/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/idm_wrapper:22315b34ce6ce588
      build_id: bd-22315b34ce6ce588_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/36/3658c92722fd7f13e5a8d4179208f66a38a2057c358e24a00665d9241beead6a/data
  conda:
    linux/amd64:
      lock_file: modules/local/idm_wrapper/.conda-lock/linux_amd64-bd-8fffb8098c99385c_1.txt
    linux/arm64:
      lock_file: modules/local/idm_wrapper/.conda-lock/linux_arm64-bd-ad0d6ca77f66f5c6_1.txt
