---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: variantstring
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-base=4.5
  - bioconda::r-variantstring=1.8.7
  - conda-forge::r-dplyr
  - conda-forge::r-optparse
  - conda-forge::r-purrr
  - conda-forge::r-readr
  - conda-forge::r-rlang
  - conda-forge::r-stringr
  - conda-forge::r-tidyr
  - conda-forge::r-validate
