name: slaf_from_stave_mlaf
description: Derive single-locus allele frequencies from stave MLAF tables
keywords:
  - slaf
  - mlaf
  - stave
  - variantstring
tools:
  - slaf_from_stave_mlaf:
      description: |
        PGEcore R script that converts stave MLAF output to SLAF tables.
      homepage: https://github.com/PlasmoGenEpi/plasmodiumdrugres
      documentation: https://plasmogenepi.github.io/PGEcore/reference/slaf_from_stave_mlaf.html
      licence: ["MIT"]
input:
  - mlaf_base:
      type: string
      description: Base name / stub for the MLAF input group
  - mlaf_input:
      type: file
      description: Multilocus allele frequency table (TSV)
      pattern: "*"
output:
  - slaf:
      - "${mlaf_input.getBaseName(3)}.aa_sl_from_ml.tsv":
          type: file
          description: Single-locus allele frequencies derived from MLAF
          pattern: "${mlaf_input.getBaseName(3)}.aa_sl_from_ml.tsv"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: versions.yml
authors:
  - "@PlasmoGenEpi"
maintainers:
  - "@PlasmoGenEpi"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/slaf_from_stave_mlaf:4c32c036540c052e
      build_id: bd-4c32c036540c052e_2
      scan_id: sc-72c48cf6d91434ef_1
    linux/arm64:
      name: community.wave.seqera.io/library/slaf_from_stave_mlaf:ace8317a34749bc2
      build_id: bd-ace8317a34749bc2_3
      scan_id: sc-f33ba67f46aa92f0_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/slaf_from_stave_mlaf:1b44980fc997ad26
      build_id: bd-1b44980fc997ad26_2
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/59/59694b9b3a63712c65ca417044bd5fb4d3927d9958fcf033bfa528a64d04caf8/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/slaf_from_stave_mlaf:d8474b4d08e5c79f
      build_id: bd-d8474b4d08e5c79f_3
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/13/13c2e282dc9f2dfe543a5995b1375589812a0952d9d0ea1f5d9db9331cd55966/data
  conda:
    linux/amd64:
      lock_file: modules/local/slaf_from_stave_mlaf/.conda-lock/linux_amd64-bd-4c32c036540c052e_2.txt
    linux/arm64:
      lock_file: modules/local/slaf_from_stave_mlaf/.conda-lock/linux_arm64-bd-ace8317a34749bc2_3.txt
