name: index_population_assignment
description: Add stable internal indices to population assignment labels
keywords:
  - population
  - index
  - assignment
tools:
  - index_population_assignment:
      description: |
        R script that maps population labels to stable indices for parallel processing.
      homepage: https://github.com/PlasmoGenEpi/plasmodiumdrugres
      documentation: https://github.com/PlasmoGenEpi/plasmodiumdrugres
      licence: ["MIT"]
input:
  - population_map:
      type: file
      description: Specimen population assignment TSV
      pattern: "*"
output:
  - population_map_indexed:
      - population_map_indexed.tsv:
          type: file
          description: Population map with stable index column
          pattern: population_map_indexed.tsv
  - population_index_lookup:
      - population_index_lookup.tsv:
          type: file
          description: Index to true population label lookup
          pattern: population_index_lookup.tsv
  - versions:
      - versions.yml:
          type: file
          description: Software versions
          pattern: versions.yml
authors:
  - "@PlasmoGenEpi"
maintainers:
  - "@PlasmoGenEpi"
containers:
  docker:
    linux/arm64:
      name: community.wave.seqera.io/library/tidyverse_tables:ffee73b5f5db8a6b
      build_id: bd-ffee73b5f5db8a6b_1
      scan_id: sc-3847eaeec6cc9ba1_1
    linux/amd64:
      name: community.wave.seqera.io/library/tidyverse_tables:c07d709009059eb9
      build_id: bd-c07d709009059eb9_1
      scan_id: sc-881821e22584e703_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/tidyverse_tables:eb638a79c53b3797
      build_id: bd-eb638a79c53b3797_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/13/13ebff194324bc29f494831d874c29068468ef584f909ef7578025288c8bee62/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/tidyverse_tables:565b0534472e6e72
      build_id: bd-565b0534472e6e72_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/c1/c18625cb21daa95ff946abd08897a21a4e747257f7282d52c070db9b268cb036/data
  conda:
    linux/amd64:
      lock_file: modules/local/index_population_assignment/.conda-lock/linux_amd64-bd-c07d709009059eb9_1.txt
    linux/arm64:
      lock_file: modules/local/index_population_assignment/.conda-lock/linux_arm64-bd-ffee73b5f5db8a6b_1.txt
