name: fem_wrapper
description: Estimate multilocus allele frequencies with FreqEstimationModel (FEM)
keywords:
  - fem
  - mlaf
  - haplotype frequency
tools:
  - FreqEstimationModel:
      description: |
        Wrapper around the FreqEstimationModel R package for MLAF estimation.
      homepage: https://github.com/aimeertaylor/FreqEstimationModel
      documentation: https://plasmogenepi.github.io/PGEcore/reference/FreqEstimationModel_wrapper.html
      licence: ["MIT"]
input:
  - aa_calls:
      type: file
      description: Amino acid call table (TSV)
      pattern: "*"
  - loci_group_table:
      type: file
      description: Loci group definition table (TSV)
      pattern: "*"
output:
  - mlaf:
      - "${aa_calls.getBaseName(3)}.aa_mlaf.tsv":
          type: file
          description: FEM multilocus allele frequency table (tuple with stub name)
          pattern: "${aa_calls.getBaseName(3)}.aa_mlaf.tsv"
  - versions:
      - versions.yml:
          type: file
          description: Software versions
          pattern: versions.yml
authors:
  - "@PlasmoGenEpi"
maintainers:
  - "@PlasmoGenEpi"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/fem_wrapper:a701cba1416a0e6a
      build_id: bd-a701cba1416a0e6a_1
      scan_id: sc-35a5b7ae8b2e0ee5_1
    linux/arm64:
      name: community.wave.seqera.io/library/fem_wrapper:ad86ed2a343c6f13
      build_id: bd-ad86ed2a343c6f13_1
      scan_id: sc-d4d0531b971cc8af_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/fem_wrapper:c1cfea3cbffdea13
      build_id: bd-c1cfea3cbffdea13_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/62/6216ed31d33ddd6e9fc77859ecfb48f843df41a45482e840fe46837e9ef07623/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/fem_wrapper:5cefe9737b74a85f
      build_id: bd-5cefe9737b74a85f_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/77/776c60e5a399e22b25f4720956c59418eca9ba6d48d943dbee73c7e5beb85780/data
  conda:
    linux/amd64:
      lock_file: modules/local/fem_wrapper/.conda-lock/linux_amd64-bd-a701cba1416a0e6a_1.txt
    linux/arm64:
      lock_file: modules/local/fem_wrapper/.conda-lock/linux_arm64-bd-ad86ed2a343c6f13_1.txt
