name: extract_allele_table
description: Extract an allele table from a PMO JSON file
keywords:
  - pmo
  - pmotools
  - allele table
tools:
  - pmotools:
      description: |
        pmotools-python extract_allele_table CLI.
      homepage: https://github.com/PlasmoGenEpi/pmotools-python
      documentation: https://github.com/PlasmoGenEpi/pmotools-python
      licence: ["MIT"]
input:
  - pmo:
      type: file
      description: PMO JSON file
      pattern: "*.json"
output:
  - allele_table:
      - allele_table.tsv:
          type: file
          description: Extracted allele table TSV
          pattern: allele_table.tsv
  - versions:
      - versions.yml:
          type: file
          description: Software versions
          pattern: versions.yml
authors:
  - "@PlasmoGenEpi"
maintainers:
  - "@PlasmoGenEpi"
containers:
  docker:
    linux/arm64:
      name: community.wave.seqera.io/library/pmotools:68db46a453531d5c
      build_id: bd-68db46a453531d5c_4
      scan_id: sc-9074ce4fde1a5047_1
    linux/amd64:
      name: community.wave.seqera.io/library/pmotools:95ef48ca9c18fa35
      build_id: bd-95ef48ca9c18fa35_4
      scan_id: sc-cecb82adfc0984fe_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/pmotools:d1b39a3d4c4e5e61
      build_id: bd-d1b39a3d4c4e5e61_4
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/18/189c44118da9b46a927fb57c5ca01460fb93bfbc4b85bcb4484036888b8d5878/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/pmotools:1431318b9150e3f5
      build_id: bd-1431318b9150e3f5_4
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/64/64de1303f6e6bdaceaaef450ff8554cd6a919b7f3a654fedafbe02c7f3546597/data
  conda:
    linux/amd64:
      lock_file: modules/local/extract_allele_table/.conda-lock/linux_amd64-bd-95ef48ca9c18fa35_4.txt
    linux/arm64:
      lock_file: modules/local/extract_allele_table/.conda-lock/linux_arm64-bd-68db46a453531d5c_4.txt
