---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: r_tidyverse
channels:
  - conda-forge
dependencies:
  - conda-forge::r-base=4.4
  - conda-forge::r-dplyr
  - conda-forge::r-magrittr
  - conda-forge::r-optparse
  - conda-forge::r-readr
  - conda-forge::r-rlang
  - conda-forge::r-stringr
  - conda-forge::r-tibble
  - conda-forge::r-tidyr
