name: estimate_allele_frequency_naive
description: Naive single-locus allele frequency estimation
keywords:
  - allele frequency
  - naive
  - slaf
tools:
  - estimate_allele_frequency_naive:
      description: |
        PGEcore R script for naive SLAF (read_count_prop or presence_absence).
      homepage: https://github.com/PlasmoGenEpi/plasmodiumdrugres
      documentation: https://github.com/PlasmoGenEpi/PGEcore/tree/develop/scripts/estimate_allele_frequency_naive
      licence: ["MIT"]
input:
  - aa_calls:
      type: file
      description: Amino acid or allele call table (TSV)
      pattern: "*"
  - method:
      type: string
      description: Estimation method (e.g. read_count_prop or presence_absence)
output:
  - slaf:
      - "${aa_calls.getBaseName(3)}.aa_slaf.tsv":
          type: file
          description: Naive single-locus allele frequency table
          pattern: "${aa_calls.getBaseName(3)}.aa_slaf.tsv"
  - versions:
      - versions.yml:
          type: file
          description: Software versions
          pattern: versions.yml
authors:
  - "@PlasmoGenEpi"
maintainers:
  - "@PlasmoGenEpi"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/pgecore_r:b3d363b44f3cab5e
      build_id: bd-b3d363b44f3cab5e_1
      scan_id: sc-0e17c1447f1a6df7_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/pgecore_r:ecb4612379d466a9
      build_id: bd-ecb4612379d466a9_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/b8/b8b5976e182bb3b8f3b3073fe7ccb663bfa240ef8476d59faf2cccf8b180fe6f/data
  conda:
    linux/amd64:
      lock_file: modules/local/estimate_allele_frequency_naive/.conda-lock/linux_amd64-bd-b3d363b44f3cab5e_1.txt
