name: Run nf-test on PR to dev with Docker

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive # Ensures submodules are fetched and updated
          fetch-depth: 0 # Fetch all history to avoid shallow clones

      - name: Ensure Git respects file permissions
        run: git config core.fileMode true

      - name: Fix R script permissions (safety net)
        run: chmod +x bin/PGEcore/scripts/**/*.R

      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "25.04.0"

      - name: Set up Docker images
        run: ./scripts/build_module_images.sh

      - name: Set up nf-test
        uses: nf-core/setup-nf-test@v1
        with:
          install-pdiff: true

      - name: Run nf-test
        run: |
          nf-test test --profile docker
